// <auto-generated />
using Lab18.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Lab18.Migrations
{
    [DbContext(typeof(ToDoAppDbContext))]
    partial class ToDoAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab18.Models.ToDo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DueDate");

                    b.Property<bool>("IsDone");

                    b.Property<int?>("ListID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("ListID");

                    b.ToTable("ToDoItems");
                });

            modelBuilder.Entity("Lab18.Models.ToDoList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("ToDoListsItems");
                });

            modelBuilder.Entity("Lab18.Models.ToDo", b =>
                {
                    b.HasOne("Lab18.Models.ToDoList", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListID");
                });
#pragma warning restore 612, 618
        }
    }
}
